const fs = require('fs');

console.log("Rebuilding applet with clean DeepCrawlLedgerView integration...");
let code = fs.readFileSync('src/app-bundle.js', 'utf8');

// 1. Fix the end of _n component up to vn = ({
let brokenSnippet = `seedUrls: e.length > 0 ? e : [\`http:`;
let vnAnchor = `vn = ({`;

let p1 = code.indexOf(brokenSnippet);
let p2 = code.indexOf(vnAnchor, p1);

if (p1 !== -1 && p2 !== -1) {
  let fixedEnd = `seedUrls: e.length > 0 ? e : [\`http://\${u}\`],
                              domainScope: y,
                              crossDomainWhitelist: t,
                              respectRobotsTxt: b,
                              autoDiscoverSitemap: x,
                              maxDepth: Math.max(1, Math.min(7, T || 3)),
                              traversalStrategy: D,
                              maxPagesPerRound: k,
                              maxFanoutPerNode: j,
                              loopTrapDepthLimit: M,
                              includeUrlRegex: w,
                              excludeUrlRegex: E,
                              urlPathPrefixWhitelist: o,
                              stripUrlQueryParams: s,
                              extractDetailPageLinkRule: {
                                regexPattern: w,
                                excludePattern: E,
                                pathKeywords: o.join(', '),
                              },
                              detailExtractors: {
                                titleSelector: le,
                                publishTimeSelector: Y,
                                timeRegexExtractor: fe,
                                contentBodySelector: pe,
                                cleanNoiseSelectors: l,
                                attachmentUrlPatterns: me,
                                nextPageSelector: he,
                              },
                              lastSaved: '刚刚',
                            }),
                            r(),
                            a && a(\`已成功保存【\${c}】深度采集策略与下钻规则！\`, \`success\`));
                          },
                          className: \`px-6 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-md transition-all cursor-pointer inline-flex items-center gap-2\`,
                          children: [
                            (0, $.jsx)(ze, { className: \`w-4 h-4\` }),
                            (0, $.jsx)(\`span\`, { children: \`保存深度采集策略\` }),
                          ],
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            }),
          }),
        ],
      })
    );
  },
  `;

  code = code.slice(0, p1) + fixedEnd + code.slice(p2);
  console.log("Repaired _n component ending.");
}

// 2. Insert defaultDeepLedgerWebsites data at top-level (before Et = { or Dt = {)
if (!code.includes("defaultDeepLedgerWebsites = [")) {
  let sitesData = [
    {
      id: "WEB-DP-001",
      svcId: "SVC-P003",
      svcName: "深度采集 · 常规日常服务 (1h/轮)",
      freq: "1h",
      name: "华夏财经新闻网",
      domain: "www.hxfinance.com",
      url: "https://www.hxfinance.com/news",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*hxfinance\\.com/(article|news|finance)/\\d+\\.html",
        pathKeywords: "/article/, /news/, .html",
        cssSelector: "a.news-title, .article-list a",
        xpathSelector: "//div[@class=\"article-list\"]//a/@href",
        excludePattern: "(cart|order|login|register|about|contact|download)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "112ms",
        needCrawl: true,
        siteCategory: "财经资讯",
        auditReason: "前置连通性正常(HTTP 200 112ms)，属国家重点财经主流资讯站点，文章文本信息密度高，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:15:30",
      },
      status: "crawling",
      todayPages: 3840,
    },
    {
      id: "WEB-DP-002",
      svcId: "SVC-P003",
      svcName: "深度采集 · 常规日常服务 (1h/轮)",
      freq: "1h",
      name: "上疆新闻官方门户",
      domain: "shangjiang.news.cn",
      url: "http://shangjiang.news.cn/finance/latest",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*shangjiang\\.news\\.cn/article/\\d{8}/\\d+\\.html",
        pathKeywords: "/article/, /detail/, .html",
        cssSelector: "a.article-link, .main-title a",
        xpathSelector: "//div[contains(@class,\"content\")]//a/@href",
        excludePattern: "(print|user_center|login|download)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "128ms",
        needCrawl: true,
        siteCategory: "官方门户",
        auditReason: "前置连通性探测正常(HTTP 200 128ms)，地方政务与主流官方门户，信息发布权威合规，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:16:10",
      },
      status: "crawling",
      todayPages: 4120,
    },
    {
      id: "WEB-DP-003",
      svcId: "SVC-P001",
      svcName: "深度采集 · 极速高频服务 (10min/轮)",
      freq: "10min",
      name: "中国经济新闻网",
      domain: "www.cet.com.cn",
      url: "http://www.cet.com.cn/macro",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*cet\\.com\\.cn/(xwsd|cjyw)/\\d+\\.html",
        pathKeywords: "/xwsd/, /cjyw/, .html",
        cssSelector: "a.headline, .news-box a",
        xpathSelector: "//div[@class=\"news-box\"]//a/@href",
        excludePattern: "(share|login|feedback)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "145ms",
        needCrawl: true,
        siteCategory: "国家级媒体",
        auditReason: "国家骨干经济新闻站点，合规采编资质，内容时效性高，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:18:02",
      },
      status: "crawling",
      todayPages: 6290,
    },
    {
      id: "WEB-DP-004",
      svcId: "SVC-P004",
      svcName: "深度采集 · 重点时效服务 (30min/轮)",
      freq: "30min",
      name: "新善闻产业观察",
      domain: "xinshanwen.com.cn",
      url: "http://xinshanwen.com.cn/news",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*xinshanwen\\.com\\.cn/detail/\\d+\\.html",
        pathKeywords: "/detail/, .html",
        cssSelector: "a.item-link",
        xpathSelector: "//a[contains(@class,\"item-link\")]/@href",
        excludePattern: "(about|contact|join)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "156ms",
        needCrawl: true,
        siteCategory: "行业智库",
        auditReason: "行业前沿产业智库与研报观察，高价值舆情资讯源，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:19:40",
      },
      status: "crawling",
      todayPages: 2950,
    },
    {
      id: "WEB-DP-005",
      svcId: "SVC-P005",
      svcName: "深度采集 · 行业综合服务 (2h/轮)",
      freq: "2h",
      name: "淘优品数码促销商城",
      domain: "mall.taoyoupin.com",
      url: "https://mall.taoyoupin.com/goods/list",
      maxDepth: 2,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*taoyoupin\\.com/item/\\d+\\.html",
        pathKeywords: "/item/, /goods/",
        cssSelector: "a.goods-item",
        xpathSelector: "//div[@class=\"goods\"]//a/@href",
        excludePattern: "(cart|buy|order|pay|login)",
      },
      verification: {
        status: "rejected_ecommerce",
        accessible: true,
        httpStatus: 200,
        latency: "94ms",
        needCrawl: false,
        siteCategory: "电商商城",
        auditReason: "识别为电商交易/商品购物平台（页面检测到购物车/订单结算/SKU价格），非目标资讯舆情，根据采集前验证规则自动跳过无需采集。",
        verifiedAt: "2026-09-29 22:20:15",
      },
      status: "skipped",
      todayPages: 0,
    },
    {
      id: "WEB-DP-006",
      svcId: "SVC-P007",
      svcName: "深度采集 · 晨间突发服务 (15min/轮)",
      freq: "15min",
      name: "金沙国际在线娱乐下注",
      domain: "bet888.jinsha-casino.xyz",
      url: "https://bet888.jinsha-casino.xyz/live",
      maxDepth: 1,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: ".*",
        pathKeywords: "",
        cssSelector: "a",
        xpathSelector: "//a/@href",
        excludePattern: "",
      },
      verification: {
        status: "blocked_illegal",
        accessible: true,
        httpStatus: 200,
        latency: "320ms",
        needCrawl: false,
        siteCategory: "涉黄赌毒违规",
        auditReason: "触犯国家网络安全与合规红线：页面检测到涉赌博彩、非法下注引流及违规低俗内容，安全合规引擎直接严禁采集并永久拦截阻断！",
        verifiedAt: "2026-09-29 22:21:05",
      },
      status: "blocked",
      todayPages: 0,
    },
    {
      id: "WEB-DP-007",
      svcId: "SVC-P008",
      svcName: "深度采集 · 巡检普查服务 (6h/轮)",
      freq: "6h",
      name: "西部前沿资讯快报 (停服)",
      domain: "west-news-timeout.org.cn",
      url: "http://west-news-timeout.org.cn/latest",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: ".*",
        pathKeywords: "",
        cssSelector: "a",
        xpathSelector: "//a/@href",
        excludePattern: "",
      },
      verification: {
        status: "unreachable",
        accessible: false,
        httpStatus: 504,
        latency: "连接超时 (>5000ms)",
        needCrawl: false,
        siteCategory: "网络故障/不可达",
        auditReason: "前置连通性探测失败：服务器响应 504 Gateway Timeout，DNS 解析异常或服务器已断网停机，无法访问。",
        verifiedAt: "2026-09-29 22:22:18",
      },
      status: "offline",
      todayPages: 0,
    },
    {
      id: "WEB-DP-008",
      svcId: "SVC-P010",
      svcName: "深度采集 · 骨干央媒服务 (3h/轮)",
      freq: "3h",
      name: "中国经济网深度智库",
      domain: "ce.cn",
      url: "http://www.ce.cn/cysc",
      maxDepth: 4,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*ce\\.cn/.*\\d{8}/\\d+\\.shtml",
        pathKeywords: "/cysc/, /xw/, .shtml",
        cssSelector: "td.font14 a, .news_list a",
        xpathSelector: "//td[@class=\"font14\"]//a/@href",
        excludePattern: "(ad|vote|video_player|special)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "98ms",
        needCrawl: true,
        siteCategory: "国家级媒体",
        auditReason: "中央重点新闻站点，经济与产业频道报道全面，前置验证正常(HTTP 200 98ms)，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:23:45",
      },
      status: "crawling",
      todayPages: 5180,
    },
    {
      id: "WEB-DP-009",
      svcId: "SVC-P011",
      svcName: "深度采集 · 日报矩阵服务 (4h/轮)",
      freq: "4h",
      name: "中经日报数字报",
      domain: "paper.ce.cn",
      url: "http://paper.ce.cn/jjrb/html/layout",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://paper\\.ce\\.cn/jjrb/html/\\d{4}-\\d{2}/\\d{2}/content_\\d+\\.htm",
        pathKeywords: "/jjrb/html/, content_",
        cssSelector: "#main-ed-articlenav a, .newslist a",
        xpathSelector: "//div[@id=\"main-ed-articlenav\"]//a/@href",
        excludePattern: "(pdf|print|help)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "135ms",
        needCrawl: true,
        siteCategory: "官方门户",
        auditReason: "数字报刊核心版面，版面目录清晰，前置连通性探测正常，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:25:10",
      },
      status: "crawling",
      todayPages: 2140,
    },
    {
      id: "WEB-DP-010",
      svcId: "SVC-P012",
      svcName: "深度采集 · 地方门户服务 (8h/轮)",
      freq: "8h",
      name: "中经宝湖综合新闻",
      domain: "baohu.ce.cn",
      url: "http://baohu.ce.cn/news",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*baohu\\.ce\\.cn/news/\\d+\\.html",
        pathKeywords: "/news/, .html",
        cssSelector: "ul.list-box a",
        xpathSelector: "//ul[@class=\"list-box\"]//a/@href",
        excludePattern: "(login|about)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "160ms",
        needCrawl: true,
        siteCategory: "官方门户",
        auditReason: "地方综合经贸门户，前置探测正常，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:26:00",
      },
      status: "crawling",
      todayPages: 1870,
    },
    {
      id: "WEB-DP-011",
      svcId: "SVC-P013",
      svcName: "深度采集 · 跨境资讯服务 (12h/轮)",
      freq: "12h",
      name: "千城国际经贸网",
      domain: "qiancheng.intl.cn",
      url: "http://qiancheng.intl.cn/global",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://.*qiancheng\\.intl\\.cn/global/\\d+\\.html",
        pathKeywords: "/global/, .html",
        cssSelector: "a.intl-link",
        xpathSelector: "//a[contains(@class,\"intl-link\")]/@href",
        excludePattern: "(cart|currency_exchange)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "178ms",
        needCrawl: true,
        siteCategory: "行业智库",
        auditReason: "跨国与区域经贸动态资讯，合规准予入库采集。",
        verifiedAt: "2026-09-29 22:27:15",
      },
      status: "crawling",
      todayPages: 3100,
    },
    {
      id: "WEB-DP-012",
      svcId: "SVC-P015",
      svcName: "深度采集 · 长周期归档服务 (24h/轮)",
      freq: "24h",
      name: "千城安安网络快讯",
      domain: "anan.qiancheng.com",
      url: "http://anan.qiancheng.com/tech",
      maxDepth: 3,
      detailExtractRules: {
        ruleType: "regex",
        regexPattern: "^https?://anan\\.qiancheng\\.com/tech/\\d+\\.html",
        pathKeywords: "/tech/, .html",
        cssSelector: "a.tech-news",
        xpathSelector: "//a[contains(@class,\"tech-news\")]/@href",
        excludePattern: "(share|app_download)",
      },
      verification: {
        status: "passed",
        accessible: true,
        httpStatus: 200,
        latency: "142ms",
        needCrawl: true,
        siteCategory: "财经资讯",
        auditReason: "科技与经贸快讯，前置探测正常，准予入库深度采集。",
        verifiedAt: "2026-09-29 22:28:40",
      },
      status: "crawling",
      todayPages: 2760,
    }
  ];

  let dtPos = code.indexOf("Dt = {");
  if (dtPos !== -1) {
    let dataCode = "defaultDeepLedgerWebsites = " + JSON.stringify(sitesData, null, 2) + ",\n  ";
    code = code.slice(0, dtPos) + dataCode + code.slice(dtPos);
    console.log("Inserted defaultDeepLedgerWebsites before Dt = {");
  }
}

// 3. Insert Yn component before vn = ({
let helperGen = fs.readFileSync('scripts/generate-clean-deep-ledger.cjs', 'utf8');
let ynExtract = helperGen.substring(helperGen.indexOf("Yn = ({"), helperGen.indexOf("};\n`"));
if (ynExtract) {
  let fullYn = ynExtract + "},\n  ";
  let vnPos = code.indexOf("\n  vn = ({");
  if (vnPos !== -1 && !code.includes("\n  Yn = ({")) {
    code = code.slice(0, vnPos) + "\n  " + fullYn + code.slice(vnPos + 1);
    console.log("Inserted Yn component before vn = ({");
  }
}

fs.writeFileSync('src/app-bundle.js', code, 'utf8');
console.log("Rebuild script finished.");
